name: v34
description: Mobile application for Volley34

version: 1.1.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  dio: ^5.8.0+1
  fluid_bottom_nav_bar: ^1.4.0
  flutter_svg: ^2.0.17
  flutter_staggered_animations: ^1.1.1
  localstorage: ^5.0.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  tuple: ^2.0.2
  dio_cache_interceptor: ^3.5.1
  collection: ^1.19.0
  like_button: ^2.0.5
  smooth_page_indicator: ^1.2.1
  feature_discovery: ^0.14.2
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  fl_chart: ^0.70.2
  flutter_spinkit: ^5.2.1
  simple_gravatar: ^1.1.0
  shared_preferences: ^2.5.2
  auto_size_text: ^3.0.0
  map_launcher: ^3.5.0
  add_2_calendar: ^3.0.1
  flutter_markdown: ^0.7.6+2
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  flutter_widget_from_html: ^0.16.0
  tinycolor2: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  page_view_indicators: ^2.0.0
  package_info_plus: ^8.3.0
  firebase_analytics: ^11.4.4
  firebase_core: ^3.12.1
  validators: ^3.0.0
  image_picker: ^1.1.2
  flutter_mailer: ^3.0.0
  modal_bottom_sheet: ^3.0.0
  badges: ^3.1.2
  upgrader: ^11.3.1
  feature_flags: ^0.1.4
  feedback: ^3.1.0
  flutter_email_sender: ^7.0.0
  maps_launcher: ^3.0.0+1
  images_picker: ^1.2.11
  flutter_sticky_header: ^0.7.0
  visibility_detector: ^0.4.0+2
  path: ^1.9.0
  flutter_image_compress: ^2.4.0
  splash_view: ^2.0.1
dev_dependencies:
  dependency_validator: ^5.0.2
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
dependency_overrides:
  flutter_svg: ^2.0.17
  flutter_plugin_android_lifecycle: 2.0.27
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/logo.png"
  image_path_ios: "assets/logo-white-background.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    #- config/
    - assets/calendar-postpone3.svg
    - assets/scoreboard.svg
    - assets/filter.svg
    - assets/attack.svg
    - assets/defense.svg
    - assets/error.svg
    - assets/gpl_licence.txt
    - assets/about.markdown
    - assets/dashboard.svg
    - assets/competition.svg
    - assets/competition-filled.svg
    - assets/clubs.svg
    - assets/map.svg
    - assets/map-filled.svg
    - assets/volleyball-filled.svg
    - assets/circle_spritesheet.png
    - assets/shield.svg
    - assets/flare/
    - assets/gymnasium_marker.png
    - assets/logo.png
    - assets/logo-big.png
    - assets/gymnasium.svg
    - assets/maps/map_style.txt
    - assets/court.png
    - assets/postponed-event.svg
    - assets/double-arrow.svg
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
          weight: 400
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



splash_screen_view:
  # Use color to set the background of your splash screen to a solid color.
  # Use background_image to set the background of your splash screen to a png image.
  # This is useful for gradients. The image will be stretch to the  size of the app.
  # Only one parameter can be used, color and background_image cannot both be set.

  color: "#262C41"
  #background_image: "assets/splashscreen_image.png"

  # Optional parameters are listed below.
  #image: assets/splashscreen_image.png
  image: assets/logo-big.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  #android: false
  #ios: false
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  #fullscreen: true

  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
